### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Broker List Activity

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1942]
Implementación de la actividad Broker List que permite ver la lista de brokers con los que el customer esta conectado y con los cuales puede iniciar una negociación. Basado en el Issue **Crypto Customer Wallet Design / Broker List view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/256) creado por @Neoperol

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4

**Comment by nelsonalfo** [comment]
Primera implementación. Los colores se los cambiare cuando se de el :+1: al diseño

![customer wallet - broker list](https://cloud.githubusercontent.com/assets/1823627/11399431/7fcfa55a-9359-11e5-87aa-944dc5bcf1fe.png)

**Comment by nelsonalfo** [comment]
Ya se implementó, faltan dialogos de ayuda
