### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Wizard Location

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1947]
Implementación del *Wizard Location* que permite configurar los lugares para intercambio del customer. El wizard va a aparecer cuando se abra la wallet por primera vez. Basado en el Issue **Crypto Customer Wallet Design / Wizard Location view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/260) creado por @Neoperol 

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
