### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Wizard Currency

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1948]
Implementación del *Wizard Currency* que permite configurar que monedas desea comprar y con que moneda desea pagar el customer de tal forma que pueda ver información como el Market Rate de las monedas seleccionadas. El wizard va a aparecer cuando se abre la wallet por primera vez. Basado en el Issue **Crypto Customer Wallet Design / Wizard Currency view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/261) creado por @Neoperol en el repositorio **bitDubai/fermat-graphic-design**

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
