### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Wizard Merchandise

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1949]
Implementación del *Wizard Merchandise* que permite configurar que crypto wallet va a asociar con la crypto customer wallet, para manejar el balance y donde va a recibir la mercancía. El wizard va a aparecer cuando se abre la wallet por primera vez. Basado en el Issue **Crypto Customer Wallet Design / Wizard Merchandise view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/262) creado por @Neoperol

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
