### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Wizard Bank Account 

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1950]
Implementación del *Wizard Bank Account* que permite configurar las cuentas bancarias donde el broker va a poder depositar la mercancía a customer en caso de que esta no sea crypto currency. El wizard va a aparecer cuando se abre la wallet por primera vez. Basado en el Issue **Crypto Customer Wallet Design / Wizard Bank Account view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/263) creado por @Neoperol 

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
