### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Open Contract Details Activity

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1951]
Implementación de la actividad *Open Contract Details* que permite ver el detalle de un contrato abierto, donde el customer puede indicar si ya pago la mercancía y ver los detalle de la negociación asociada. Basado en el Issue **Crypto Customer Wallet Design / Contract Detail view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/258) creado por @Neoperol en el repositorio **bitDubai/fermat-graphic-design**

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
