### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Negotiation Details Activity

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1954]
Implementación de la actividad *Negotiation Details* que permite a un customer ver y editar los detalles de una negociación, bien sea cancelándola, aceptándola o modificando alguno de los pasos o clausulas. Basado en el Issue **Crypto Customer Wallet Design / Negotiation Detail view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/280) creado por @Neoperol

@jorgeejgonzalez 

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
