### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Settings Currency Fragment

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1983]
Implementación del fragmento *Settings Currency* que permite configurar que monedas desea comprar y con que moneda desea pagar el customer de tal forma que pueda ver información como el Market Rate de las monedas seleccionadas. El fragmanto va a ser accesible desde la actividad *Settings*. Basado en el Issue **Crypto Customer Wallet Design / Settings Currency view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/288) creado por @Neoperol

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
