### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Settings Merchandise Fragment

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1984]
Implementación del fragmento *Settings Merchandise* que permite configurar que crypto wallet va a asociar con la crypto customer wallet, para manejar el balance y donde va a recibir la mercancía. El fragmanto va a ser accesible desde la actividad *Settings*. Basado en el Issue **Crypto Customer Wallet Design / Settings Merchandise view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/286) creado por @Neoperol

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
