### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Settings Bank Account Fragment

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1985]
Implementación del fragmento *Settings Bank Account* que permite configurar las cuentas bancarias donde el broker va a poder depositar la mercancía a customer en caso de que esta no sea crypto currency. El fragmanto va a ser accesible desde la actividad *Settings*. Basado en el Issue **Crypto Customer Wallet Design / Settings Bank Account view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/285) creado por @Neoperol

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
