### ISSUE TITLE
CBP - Reference Wallet - Crypto Customer - GUI - Settings Location Fragment

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1987]
Implementación del fragmento *Settings Location* que permite configurar los lugares para intercambio del customer. El fragmanto va a ser accesible desde la actividad *Settings*. Basado en el Issue **Crypto Customer Wallet Design / Settings Location view Design** (https://github.com/bitDubai/fermat-graphic-design/issues/287) creado por @Neoperol 

@jorgeejgonzalez

Issue Padre: #1910

**Comment by arnaldos** [comment]
@m471c4
