### ISSUE TITLE
CBP - Reference Wallet - Crypto Broker - GUI - Settings Location Fragment

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#1988]
Implementación del fragmento *Settings Location* que permite configurar los lugares para intercambio del broker. El fragmanto va a ser accesible desde la actividad *Settings*. Basado en el Issue **Broker Wallet Design / Settings Location view Design** (bitDubai/fermat-graphic-design#284) creado por @Neoperol

@jorgeejgonzalez

Issue Padre: #1827

**Comment by arnaldos** [comment]
@m471c4
