### ISSUE TITLE
Refactoring WPD Enums

### ISSUE THREAD

**Issue by lnacosta** [Fermat-ORG/fermat#3561]
fermat-api com.bitdubai.fermat_api.layer.all_definition.enums

WalletType
WalletFactoryProjectState
WalletCategory
NicheWallet
ReferenceWallet

**Comment by lnacosta** [comment]
@furszy please, check this with Nerio.

**Comment by nindriago** [comment]
Review Enums:
WalletType
WalletCategory
NicheWallet
ReferenceWallet

Refactor is not possible yet, because, other class ussing in fermat_api and fermat_api dont see WPD_API in this case.

@lnacosta  @furszy

**Comment by lnacosta** [comment]
We should make a list of the classes that are using those enums.
Wallets are known after WPD. The interface InstalledWallet musn't be in the common api.

**Comment by nindriago** [comment]
package com.bitdubai.fermat_api.layer.all_definition.enums.WalletCategory;

conflicts with:

package com.bitdubai.sub_app.wallet_manager.structure.provisory_classes.InstalledWallet;

Exist 2 Interfaces with same Name and both are in use

package com.bitdubai.fermat_api.layer.dmp_module.wallet_manager.InstalledWallet;
package com.bitdubai.fermat_wpd_api.layer.wpd_middleware.wallet_manager.interfaces.InstalledWallet;

which Interfaces are use?
@lnacosta  @furszy

**Comment by lnacosta** [comment]
We should use the wpd interface, I think. We start to know about Wallets in WPD platform.

@acostarodrigo am I right?

**Comment by lnacosta** [comment]
@acostarodrigo  could you see this?
