### ISSUE TITLE
Refactoring BCH Enums

### ISSUE THREAD

**Issue by lnacosta** [Fermat-ORG/fermat#3564]
fermat-api com.bitdubai.fermat_api.layer.all_definition.enums

CryptoCurrencyVault
CryptoAssetVault
VaultType

**Comment by lnacosta** [comment]
@acostarodrigo  could you inform the status of this issue?

**Comment by lnacosta** [comment]
@acostarodrigo have you seen this issue?

**Comment by acostarodrigo** [comment]
si querido...me llegan tus mails ...pero hay otras prioridades...

yo te aviso

**Comment by lnacosta** [comment]
sorry man, i'm just trying to keep the issues up to date.
