### ISSUE TITLE
Refactoring Communication components

### ISSUE THREAD

**Issue by lnacosta** [Fermat-ORG/fermat#3565]
fermat-api com.bitdubai.fermat_api.layer.all_definition.components

please, move to the correspondant api (P2P)

**Comment by lnacosta** [comment]
@hendry19901990  could you inform the status of this issue?

**Comment by lnacosta** [comment]
is already fixed ?

**Comment by lnacosta** [comment]
@hendry19901990 please, can you explain in a few words why we're not following this task?

**Comment by hendry19901990** [comment]
We agreed that we can not do it because there is cyclic Redundancy in the project

**Comment by lnacosta** [comment]
It will be no need for this after new version implementation.
