### ISSUE TITLE
Refactoring DeveloperIdentity

### ISSUE THREAD

**Issue by lnacosta** [Fermat-ORG/fermat#3567]
fermat-api com.bitdubai.fermat_api.layer.pip_Identity.developer.interfaces

move where it belongs (WPD)

**Comment by lnacosta** [comment]
@acostarodrigo could you inform the status of this issue?

**Comment by lnacosta** [comment]
@acostarodrigo have you seen this issue?

**Comment by nindriago** [comment]
this refactor, only is possible changing too:

package com.bitdubai.fermat_api.layer.all_definition.navigation_structure.WalletNavigationStructure;

ok???
@lnacosta @acostarodrigo

**Comment by lnacosta** [comment]
yep
