### ISSUE TITLE
Fermat Money Structure -> Discussion

### ISSUE THREAD

**Issue by lnacosta** [Fermat-ORG/fermat#4010]
### Money
 * Digital Money
   * Virtual Currency
     * Fiat
     * Non-Fiat
   * Crypto Currency
     * Fiat
     * Non-Fiat
   * Bank Money
     * Fiat
     * Non-Fiat
   * Crypto Commodity Money (dinero respaldado por crypto currency)
     * Fiat
     * Non-Fiat
     
 * Cash Money
   * Physical Money
     * Fiat
     * Non-Fiat

## ¿Quién lo emite?
Money
 * Fiat Money (Dinero respaldado por fuerza de ley)
 * Non-Fiat Money (Dinero no respaldado por fuerza de ley) - Private Money / Supra-Nacional

### Interface Structure Definition

Money
-getType()     // MoneyType    (DIGITAL / CASH)
-getSubType()  // MoneySubType (interface)
-getOrigin()   // MoneyOrigin  (FIAT / NON-FIAT)

DigitalMoneySubType extends MoneySubType()
CashMoneySubType    extends MoneySubType()

DigitalMoney extends Money()

CashMoney extends Money()

VirtualCurrency      implements DigitalMoney()
CryptoCurrency       implements DigitalMoney()
BankMoney            implements DigitalMoney()
CryptoCommodityMoney implements DigitalMoney()

PhysycalMoney        implements CashMoney()

@Luis-Fernando-Molina @abicelis

**Comment by Luis-Fernando-Molina** [comment]
CASH por definicion ya significa dinero fisico pero a su vez tiene ciertas propiedades que lo diferencian del dinero en el banco, como que es al portador, y que las transacciones con el son anonimas. Si usamos esas propiedades como definicion entonces si pudieras tener:

CASH
  * Phisycal Money
  * Electronic Cash (que ahi de nuevo entran cosas como crypto currecies, acordate que Bitcoin = P2P Electronic Cash payment system

Para que no quede una referencia circular entre electronic cash y crypto currency, yo solo dejaria CASH sin el subtipo de Phisical Money


------------------

yo reemplazaria -getOrigin() // MoneyOrigin (FIAT / NON-FIAT) por un isFIAT()
