### ISSUE TITLE
CHT-Chat Platform App Views

### ISSUE THREAD

**Issue by josejcb** [Fermat-ORG/fermat#4114]
Se adjunta diseño conceptual de las vistas de esta plataforma. Se desea una revisión para que antes de generarlas agreguemos lo que pudiera hacer falta, asi disminuimos la cantidad de correcciones en tiempo de desarrollo. @Luis-Fernando-Molina @franklinmarcano1970 @darkestpriest 
[CHAT Project.pdf](https://github.com/bitDubai/fermat/files/73340/CHAT.Project.pdf)

**Comment by Luis-Fernando-Molina** [comment]
Hola Jose, te recomiendo que escriba el contenido que quieras mostrar directamente en el caso o un archivo en github asi no descargamos archivos en nuestras PCs que luegon quedan cosas de medio mundo por ahi. saludos

**Comment by josejcb** [comment]
Mea culpa. Debí pasarles el link del proyecto para que allí lo comenten. https://ninjamock.com/s/8TDDS.

**Comment by darkestpriest** [comment]
@josejcb el diseño me parece bien, sencillo y práctico. Vamos a incluir a @GaboHub y a @lostwood en este issue para ver que opinan del diseño conceptual y así verificamos las opiciones y comentarios que puedan tener al respecto.

**Comment by franklinmarcano1970** [comment]
Me parece bien.
@Luis-Fernando-Molina Seria bueno Luis que etiquetemos a @arnaldos  y a Gregory para que comienzen a hacer sus propuestas de UIX.

**Comment by Luis-Fernando-Molina** [comment]
seguro, de todas formas la idea es que se vea lo mas parecido a Whasapp posible, que es uno de los sistemas de chat mas conocidos del mundo. Salvo que no diga whatsapp el resto debiera ser practicamente igual.

**Comment by franklinmarcano1970** [comment]
Perfecto, bueno jose comienza con la propuesta basica para comenzar para probar.

**Comment by josejcb** [comment]
@arnaldos @Neoperol Saludos, la plataforma cht requiere un diseño de UI/UX, solicitamos una propuesta o recomendación de como se debería ver. Acá están los diseños básicos del concepto, la idea está basada en apps de mensajería instantánea ya conocidas y de uso común.
