### ISSUE TITLE
Improve the unit test coverage: fermat-cbp-plugin-business-transaction-customer-online-payment-bitdubai

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#4516]
This issue is part #3617
Check the guide lines for the Unit test in fermat:
[Unit Test Guidelines in spanish] (https://github.com/jorgeejgonzalez/fermat/wiki/Unit-Testing)

If this is the first time you're going to run a test coverage , you must follow these steps:
In the project main folder, execute in shell the next command:
```shell
gradle project
```
This command will download all the missing dependencies.

To check the coverage using:
```shell
gradle : fermat-cbp-plugin-business-transaction-customer-online-payment-bitdubai:testCoverage
```
This task is included in **build.gradle**
Assignee: @alexanderejm

**Comment by alexanderejm** [comment]
Issue Fixed
