### ISSUE TITLE
Desktop - Settings - Display APPs

### ISSUE THREAD

**Issue by furszy** [Fermat-ORG/fermat#4517]
@Neoperol @Luis-Fernando-Molina 

Gregory, esto es lo que hablamos. Fijate de hacerme un wireframe para poder implementarlo.
Pedido:
"Agregar un icono al lado las networks en el panel de settings, que represente el estado del software a mostrar en los desktops. Los diferentes estados pueden ser: Release  | Beta | Alpha | Dev . El estado lo vamos a mostrar en otro color debajo del nombre del icono, como en una tercera linea (en verde). El label del icono debe ser "Display APPs". El estado del software se debe leer de cada componente Android (interfaz grafica). La idea es que apretando ese icono se va pasando por los diferentes estados y los desktops deben filtrar automaticamente lo que no corresponde".

**Comment by Neoperol** [comment]
![fermat-app-launcher_settings_display](https://cloud.githubusercontent.com/assets/6201081/12399182/9d4de752-bdea-11e5-8de6-54137b940fc4.jpg)


@furszy @Luis-Fernando-Molina 

Si, solo se van a manejar 4 opciones se pueden mostrar las 4 opciones y que el icono represente la que esta activa en estos momentos. 
La otra opción es usar un spinner. 
No lo hago con la version actual porque no tengo esos editables. Esto es solo para mostrar la diagramacion que se puede usar.

**Comment by Luis-Fernando-Molina** [comment]
es un solo icono que cuando lo tocas cambia a las 4 posible posiciones, y esta en la misma fila que el resto de los iconos actuales.

**Comment by Neoperol** [comment]
![fermat-app-launcher_settings_display](https://cloud.githubusercontent.com/assets/6201081/12405816/91205198-be19-11e5-839b-869c49b5c339.jpg)

@furszy 
@arnaldos 

Ok, el nuevo controlador del display de apps estaria en el mismo row que se encuentran los otros. 
Y el comportamiento del boton seria un toggle entre las 4 opciones, cambiando el nombre de la opción seleccionada. 
@arnaldos Solo hay que hacer el icono correspondiente a esta acción.

**Comment by furszy** [comment]
@Luis-Fernando-Molina 
Parece que cada uno entendió una cosa distinta de lo que se quiere hacer, por mi parte creí que era un icono que cuando lo tocabas pasaba a alpha,beta,etc. y así se filtraban las cosas. Que un texto abajo de wallets distinguía en que pantalla estabas diciendo el estado de las aplicaciones que se encuentra viendo el usuario.
Si no es así, esto me pareció la forma más sencilla y visual para que el usuario sepa en donde se encuentra y pueda e ir viendo los estados de las aplicaciones.

**Comment by Luis-Fernando-Molina** [comment]
aclaro de nuevo:

Es un solo icono que cuando lo tocas va cambiando entre los 4 posibles estados. El cambio se refleja en que el icono en si mismo cambia, pero también cambia el texto que dice abajo del nombre del icono. 

El nombre del icono es : "APPs Displayed"
y los posibles estatus "Release, Beta, Alpha, Dev"

En las APPs no habiamos hablado de poner nada hasta ahora. Pudiera ser que tambien se le agregue el estado debajo del nombre para que el usuario esté conciente de donde está entrando. A las aplicaciones en estado Release no se le debiera agregar nada debajo del nombre. 

Release es el estado por defecto que tendría el icono / switch este que estamos discutiendo.

**Comment by furszy** [comment]
@arnaldos como quedamos con esto?

**Comment by arnaldos** [comment]
@furszy ajustes del settings 

![settings-app-settings-launcher](https://cloud.githubusercontent.com/assets/13594347/12938451/0fdd37a8-cf86-11e5-93a9-a41bc416da2d.png)

![settings-app-settings-launcher2](https://cloud.githubusercontent.com/assets/13594347/12938452/0fe30d7c-cf86-11e5-9ade-32d94bb5ee62.png)

**Comment by furszy** [comment]
completado
