### ISSUE TITLE
Android api - Money selector custom view

### ISSUE THREAD

**Issue by furszy** [Fermat-ORG/fermat#4636]
Se debe realizar un template de un selector de moneda que pueda ser usado por todas las plataformas.
Propongamos ideas de como se debe ver el más basico de todos y a partir de ahí lo hacemos custom al estilo Fermat.  @arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
De alguna manera debe involucrar la bandera de cada pais. Como un boton forrado como una bandera, o algo asi, pero debe estar. Me imagino que se puede conseguir por ahi no hace falta que se haga, pero si se tiene que hacer se hace.

Debe incluir tambien el simbolo de $ libra o lo que sea (debe haber un standard unicode o algo asi) el codigo de tres letras del pais USD  , CAD, etc. y el nombre completo "United States Dollar". 

El usuario de la vista debiera poder setear por parametro si quiere que alguna de las cosas no se muestre en su caso o algun otro parametro que modifique la vaina, como por ejemplo que moneda debiera salir primero mas alla del orden de la lista, el orden de la lista, etc.

**Comment by furszy** [comment]
completado
