### ISSUE TITLE
CCP - Intra User Community -  Several Issues 

### ISSUE THREAD

**Issue by Exilum** [Fermat-ORG/fermat#4641]
1.- The google plus icon that appears when two intra users are connected or connections needs to be changed by another one that represents a community connection.
2.- Add an icon to the over every picture when a connection request was sent in order to know that the person is waiting for a response.
3.- When the drawer picture is touched the user has to be routed to the identity creation screen in order to allow him to change the name and phrase.
4.- The intra user cache needs to be checked.

**Comment by Exilum** [comment]
@furszy please assign this issue to me.

**Comment by Exilum** [comment]
Point 4 is closed.

**Comment by nattyco** [comment]
Point 3 fixed

**Comment by nattyco** [comment]
Point 1 and 2 fixed, point 3 It will be resolved in other issue

**Comment by nattyco** [comment]
point 4 will be resolved in issue #4641
