### ISSUE TITLE
CCP - Reference Wallet - Several Android issues.

### ISSUE THREAD

**Issue by Exilum** [Fermat-ORG/fermat#4643]
1.- The drawer picture is being shown pixeled.
2.- On the send and receive form was observed the following : when you are typing the name of an user the app shut itself down suddently.
3.- On the donut was observed the following : when you change from btc to bits, if the number resulting  is too long and it does not fit in the space, the number takes the following lower line.

**Comment by nattyco** [comment]
Point 2 fixed

**Comment by nattyco** [comment]
Point 1 will be solved in issue  #4879

**Comment by nattyco** [comment]
Point 3 Fixed
