### ISSUE TITLE
CBP - Network Service - Transaction Transmission - Check the plugin functionality

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#4749]
Parent: #3079
Right now this plugin has problem to send messages to another network service. Is required to check and fix this connection problems.

**Comment by GaboHub** [comment]
@darkestpriest 
This NS is sending messages now. but the remote device get this null pointer.
 --------------------------------------------------------------------- 
02-10 01:12:49.143 2817-2849/? I/System.out:  WsCommunicationsTyrusCloudClientChannel - Starting method onMessage(String)
02-10 01:12:49.143 2817-2849/? I/System.out:  WsCommunicationsTyrusCloudClientChannel - decoding fermatPacket with client-identity 
02-10 01:12:49.143 2817-2849/? I/System.out:  WsCommunicationsTyrusCloudClientChannel - validateFermatPacketSignature
02-10 01:12:49.144 2817-2849/? I/System.out: ComponentConnectionRespondTyrusPacketProcessor - vpnServerUri to connect = ws://52.35.64.221:9090/fermat/vpn/
02-10 01:12:49.145 2817-2849/? I/System.out: GUARDANDO LA CONEXION EN CACHE CON NS = TRANSACTION_TRANSMISSION
02-10 01:12:49.145 2817-2849/? I/System.out: GUARDANDO LA CONEXION EN CACHE CON PK = 04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34
02-10 01:12:49.706 2817-2961/? I/System.out:  --------------------------------------------------------------------- 
02-10 01:12:49.706 2817-2961/? I/System.out:  WsCommunicationVPNClient - Starting method onOpen
02-10 01:12:49.706 2817-2961/? I/System.out:  WsCommunicationVPNClient - Session id = afc0b430-42a9-4999-8a38-fd4a3e970d5e
02-10 01:12:49.751 2817-2849/? I/System.out:  --------------------------------------------------------------------- 
02-10 01:12:49.751 2817-2849/? I/System.out:  WsCommunicationsTyrusCloudClientChannel - Starting method onMessage(String)
02-10 01:12:49.751 2817-2849/? I/System.out:  WsCommunicationsTyrusCloudClientChannel - decoding fermatPacket with client-identity 
02-10 01:12:49.752 2817-2849/? I/System.out:  WsCommunicationsTyrusCloudClientChannel - validateFermatPacketSignature
02-10 01:12:49.752 2817-2849/? I/System.out: CompleteComponentConnectionRequestTyrusPacketProcessor - processingPackage = 
02-10 01:12:49.752 2817-2849/? I/System.out: CompleteComponentConnectionRequestTyrusPacketProcessor - networkServiceType = TRANSACTION_TRANSMISSION
02-10 01:12:49.752 2817-2849/? I/System.out: CompleteComponentConnectionRequestTyrusPacketProcessor - applicantComponent = transactiontransmissionnetworkservice[04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943]
02-10 01:12:49.752 2817-2849/? I/System.out: CompleteComponentConnectionRequestTyrusPacketProcessor - remoteComponent    = transactiontransmissionnetworkservice[04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34]
02-10 01:12:49.753 2817-2849/? I/System.out: CompleteComponentConnectionRequestTyrusPacketProcessor - Raised a event = P2pEventType.COMPLETE_COMPONENT_CONNECTION_REQUEST_NOTIFICATION
02-10 01:12:49.753 2817-2849/? I/System.out: WsCommunicationVPNClientManagerAgent getActiveVpnConnection - remotePlatformComponentProfile = transactiontransmissionnetworkservice
02-10 01:12:49.753 2817-2849/? I/System.out: WsCommunicationVPNClientManagerAgent getActiveVpnConnection - applicantNetworkServiceType = TRANSACTION_TRANSMISSION
02-10 01:12:49.753 2817-2849/? I/System.out: WsCommunicationVPNClientManagerAgent networkServiceType available= TRANSACTION_TRANSMISSION
02-10 01:12:49.753 2817-2849/? I/System.out: WsCommunicationVPNClientManagerAgent instance.vpnClientActiveCache.containsKey(applicantNetworkServiceType) = true
02-10 01:12:49.753 2817-2849/? I/System.out: WsCommunicationVPNClientManagerAgent - instance.vpnClientActiveCache.get(applicantNetworkServiceType).size() = 1
02-10 01:12:49.753 2817-2849/? I/System.out: ---------------------CLAVE DISPONIBLES:[TRANSACTION_TRANSMISSION]------------------------------------
02-10 01:12:49.753 2817-2849/? I/System.out: ---------------------CLAVES BUSCADA:04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34------------------------------------
02-10 01:12:49.753 2817-2849/? I/System.out: -----------------------
02-10 01:12:49.753 2817-2849/? I/System.out: TRANSACTION TRANSMISSION INCOMING CONNECTION  -----------------------
02-10 01:12:49.753 2817-2849/? I/System.out: -----------------------
02-10 01:12:49.753 2817-2849/? I/System.out:  A: transactiontransmissionnetworkserviceCompleteComponentConnectionRequestNotificationEventHandler - handleEvent platformEvent =CompleteComponentConnectionRequestNotificationEvent{networkServiceTypeApplicant=TRANSACTION_TRANSMISSION, remoteComponent=PlatformComponentProfileCommunication{alias='transactiontransmissionnetworkservice', identityPublicKey='04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34', name='Transaction Transmission Network Service', location =null, platformComponentType=NETWORK_SERVICE, networkServiceType=TRANSACTION_TRANSMISSION, communicationCloudClientIdentity='04497338CCF49EC7255494119478B379DDD34021DDE33655F09F6068D414BFE120CF8DF1C6A3FD6AD8E22C088808072CB7D14F896CA911718F2827C6CD077A42C6', extraData = null}, applicantComponent=PlatformComponentProfileCommunication{alias='transactiontransmissionnetworkservice', identityPublicKey='04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943', name='Transaction Transmission Network Service', location =null, platformComponentType=NETWORK_SERVICE, networkServiceType=TRANSACTION_TRANSMISSION, communicationCloudClientIdentity='04570DD4620558106616592B071DF51FCB33DD50AE65A739C78F294AEBFD94A9788CF2328788016592633C83D003EEAB2659780DCC6377B7B4685480CE35E088A8', extraData = null}}
02-10 01:12:49.754 2817-2849/? I/System.out: CompleteComponentConnectionRequestNotificationEventHandler - handleEvent platformEvent =CompleteComponentConnectionRequestNotificationEvent{networkServiceTypeApplicant=TRANSACTION_TRANSMISSION, remoteComponent=PlatformComponentProfileCommunication{alias='transactiontransmissionnetworkservice', identityPublicKey='04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34', name='Transaction Transmission Network Service', location =null, platformComponentType=NETWORK_SERVICE, networkServiceType=TRANSACTION_TRANSMISSION, communicationCloudClientIdentity='04497338CCF49EC7255494119478B379DDD34021DDE33655F09F6068D414BFE120CF8DF1C6A3FD6AD8E22C088808072CB7D14F896CA911718F2827C6CD077A42C6', extraData = null}, applicantComponent=PlatformComponentProfileCommunication{alias='transactiontransmissionnetworkservice', identityPublicKey='04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943', name='Transaction Transmission Network Service', location =null, platformComponentType=NETWORK_SERVICE, networkServiceType=TRANSACTION_TRANSMISSION, communicationCloudClientIdentity='04570DD4620558106616592B071DF51FCB33DD50AE65A739C78F294AEBFD94A9788CF2328788016592633C83D003EEAB2659780DCC6377B7B4685480CE35E088A8', extraData = null}}
02-10 01:12:49.754 2817-2849/? I/System.out: CompleteComponentConnectionRequestNotificationEventHandler - handleEvent platformEvent =CompleteComponentConnectionRequestNotificationEvent{networkServiceTypeApplicant=TRANSACTION_TRANSMISSION, remoteComponent=PlatformComponentProfileCommunication{alias='transactiontransmissionnetworkservice', identityPublicKey='04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34', name='Transaction Transmission Network Service', location =null, platformComponentType=NETWORK_SERVICE, networkServiceType=TRANSACTION_TRANSMISSION, communicationCloudClientIdentity='04497338CCF49EC7255494119478B379DDD34021DDE33655F09F6068D414BFE120CF8DF1C6A3FD6AD8E22C088808072CB7D14F896CA911718F2827C6CD077A42C6', extraData = null}, applicantComponent=PlatformComponentProfileCommunication{alias='transactiontransmissionnetworkservice', identityPublicKey='04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943', name='Transaction Transmission Network Service', location =null, platformComponentType=NETWORK_SERVICE, networkServiceType=TRANSACTION_TRANSMISSION, communicationCloudClientIdentity='04570DD4620558106616592B071DF51FCB33DD50AE65A739C78F294AEBFD94A9788CF2328788016592633C83D003EEAB2659780DCC6377B7B4685480CE35E088A8', extraData = null}}
02-10 01:13:04.178 2817-2961/? I/System.out:  --------------------------------------------------------------------- 
02-10 01:13:04.178 2817-2961/? I/System.out:  WsCommunicationVPNClient - Starting method onMessage(String)
02-10 01:13:04.178 2817-2961/? I/System.out:  WsCommunicationVPNClient - encode fermatPacket {"id":"9fb0e97c-6bad-49e6-9411-c32041f8e02d","sender":"0470E99C976114508B8E30640F866BE0DDBDE2B1350776F27F6DCB8CD317CD80FE4F42CFD7DBF7D34C2966821B730F4B78FE3DDAB696BA74A24F4F7353C133E50A","destination":"047AC83CDEDAC89FCE17DFD7F283204449C6D905632562391C23DD25DD04CBA5CD03B0F906EA5B53F675F71B7AB14C26A421C60209F68315E1D642DE616C62C361","fermatPacketType":"MESSAGE_TRANSMIT","messageContent":"{\"id\":\"bcecae73-d9e0-4873-b81e-35d4b805da19\",\"sender\":\"04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34\",\"receiver\":\"04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943\",\"content\":\"{\\\"contractHash\\\":\\\"888052D7D718420BD197B647F3BB04128C9B71BC99DBB7BC60E78BDAC4DFC6E2\\\",\\\"contractId\\\":\\\"888052D7D718420BD197B647F3BB04128C9B71BC99DBB7BC60E78BDAC4DFC6E2\\\",\\\"contractTransactionStatus\\\":\\\"CONTRACT_OPENED\\\",\\\"negotiationId\\\":\\\"550e8400-e29b-41d4-a716-446655440000\\\",\\\"pendingFlag\\\":false,\\\"receiverId\\\":\\\"04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943\\\",\\\"receiverType\\\":\\\"NETWORK_SERVICE\\\",\\\"senderId\\\":\\\"04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34\\\",\\\"senderType\\\":\\\"NETWORK_SERVICE\\\",\\\"timestamp\\\":2016,\\\"transactionId\\\":\\\"550e8400-e29b-41d4-a716-446655440000\\\",\\\"transactionTransmissionStates\\\":\\\"SENT\\\",\\\"transactionType\\\":\\\"TRANSACTION_HASH\\\"}\",\"shippingTimestamp\":\"Feb 10, 2016 1:13:03 AM\",\"deliveryTimestamp\":\"Dec 31, 1969 7:00:00 PM\",\"fermatMessagesStatus\":\"PENDING_TO_SEND\",\"signature\":\"\",\"fermatMessageContentType\":\"TEXT\"}","signature":""}
02-10 01:13:04.180 2817-2961/? I/System.out:  WsCommunicationsCloudClientChannel - decode fermatPacket FermatPacketCommunication{destination='047AC83CDEDAC89FCE17DFD7F283204449C6D905632562391C23DD25DD04CBA5CD03B0F906EA5B53F675F71B7AB14C26A421C60209F68315E1D642DE616C62C361', id=9fb0e97c-6bad-49e6-9411-c32041f8e02d, sender='0470E99C976114508B8E30640F866BE0DDBDE2B1350776F27F6DCB8CD317CD80FE4F42CFD7DBF7D34C2966821B730F4B78FE3DDAB696BA74A24F4F7353C133E50A', fermatPacketType=MESSAGE_TRANSMIT, messageContent={"id":"bcecae73-d9e0-4873-b81e-35d4b805da19","sender":"04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34","receiver":"04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943","content":"{\"contractHash\":\"888052D7D718420BD197B647F3BB04128C9B71BC99DBB7BC60E78BDAC4DFC6E2\",\"contractId\":\"888052D7D718420BD197B647F3BB04128C9B71BC99DBB7BC60E78BDAC4DFC6E2\",\"contractTransactionStatus\":\"CONTRACT_OPENED\",\"negotiationId\":\"550e8400-e29b-41d4-a716-446655440000\",\"pendingFlag\":false,\"receiverId\":\"04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943\",\"receiverType\":\"NETWORK_SERVICE\",\"senderId\":\"04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34\",\"senderType\":\"NETWORK_SERVICE\",\"timestamp\":2016,\"transactionId\":\"550e8400-e29b-41d4-a716-446655440000\",\"transactionTransmissionStates\":\"SENT\",\"transactionType\":\"TRANSACTION_HASH\"}","shippingTimestamp":"Feb 10, 2016 1:13:03 AM","deliveryTimestamp":"Dec 31, 1969 7:00:00 PM","fermatMessagesStatus":"PENDING_TO_SEND","signature":"","fermatMessageContentType":"TEXT"}, signature='}
02-10 01:13:04.180 2817-2961/? I/System.out:  WsCommunicationVPNClient - validateFermatPacketSignature
02-10 01:13:04.180 2817-2961/? I/System.out:  WsCommunicationVPNClient - isValid = true
02-10 01:13:04.180 2817-2961/? I/System.out: WsCommunicationVPNClient - messageContentJsonStringRepresentation = {"id":"bcecae73-d9e0-4873-b81e-35d4b805da19","sender":"04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34","receiver":"04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943","content":"{\"contractHash\":\"888052D7D718420BD197B647F3BB04128C9B71BC99DBB7BC60E78BDAC4DFC6E2\",\"contractId\":\"888052D7D718420BD197B647F3BB04128C9B71BC99DBB7BC60E78BDAC4DFC6E2\",\"contractTransactionStatus\":\"CONTRACT_OPENED\",\"negotiationId\":\"550e8400-e29b-41d4-a716-446655440000\",\"pendingFlag\":false,\"receiverId\":\"04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943\",\"receiverType\":\"NETWORK_SERVICE\",\"senderId\":\"04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34\",\"senderType\":\"NETWORK_SERVICE\",\"timestamp\":2016,\"transactionId\":\"550e8400-e29b-41d4-a716-446655440000\",\"transactionTransmissionStates\":\"SENT\",\"transactionType\":\"TRANSACTION_HASH\"}","shippingTimestamp":"Feb 10, 2016 1:13:03 AM","deliveryTimestamp":"Dec 31, 1969 7:00:00 PM","fermatMessagesStatus":"PENDING_TO_SEND","signature":"","fermatMessageContentType":"TEXT"}
02-10 01:13:04.182 2817-2961/? I/System.out: WsCommunicationVPNClient - fermatMessage = FermatMessageCommunication{content={"contractHash":"888052D7D718420BD197B647F3BB04128C9B71BC99DBB7BC60E78BDAC4DFC6E2","contractId":"888052D7D718420BD197B647F3BB04128C9B71BC99DBB7BC60E78BDAC4DFC6E2","contractTransactionStatus":"CONTRACT_OPENED","negotiationId":"550e8400-e29b-41d4-a716-446655440000","pendingFlag":false,"receiverId":"04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943","receiverType":"NETWORK_SERVICE","senderId":"04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34","senderType":"NETWORK_SERVICE","timestamp":2016,"transactionId":"550e8400-e29b-41d4-a716-446655440000","transactionTransmissionStates":"SENT","transactionType":"TRANSACTION_HASH"}, id=bcecae73-d9e0-4873-b81e-35d4b805da19, sender='04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34', receiver='04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943', shippingTimestamp=2016-02-10 01:13:03.0, deliveryTimestamp=1969-12-31 19:00:00.0, fermatMessagesStatus=PTS, signature='', fermatMessageContentType=TXT}
02-10 01:13:04.182 2817-2961/? I/System.out: WsCommunicationVPNClient - pendingIncomingMessages.size() = 1
02-10 01:13:04.514 2817-2865/? I/System.out:  WsCommunicationsCloudClientSupervisorConnectionAgent - Connection is Open = true
02-10 01:13:04.514 2817-2865/? I/System.out:  WsCommunicationsTyrusCloudClientChannel - Sending ping to the node...
02-10 01:13:04.837 2817-2850/? I/System.out:  WsCommunicationsTyrusCloudClientChannel - Pong message receive from server = 偉乇
02-10 01:13:06.193 2817-2963/? I/System.out: CommunicationNetworkServiceLocal - onMessageReceived 
02-10 01:13:06.193 2817-2963/? I/System.out: {"contractHash":"888052D7D718420BD197B647F3BB04128C9B71BC99DBB7BC60E78BDAC4DFC6E2","contractId":"888052D7D718420BD197B647F3BB04128C9B71BC99DBB7BC60E78BDAC4DFC6E2","contractTransactionStatus":"CONTRACT_OPENED","negotiationId":"550e8400-e29b-41d4-a716-446655440000","pendingFlag":false,"receiverId":"04EC4D470D0463E700D562874F12FA95E2F946677ED3BFF4D643644886A8763D9771909FAC9A0460C45A4D9A67B0CF77B1504F6B29F4ABF48B85B7BF60EA908943","receiverType":"NETWORK_SERVICE","senderId":"04760ED839EFBFE037DDED2D9BEF6F788E4E9EEF3AE7D35A4F6667D8630723867272C75F5525F5916C925A57651322D884394DC0114634D9BDDE2DD97D15B8ED34","senderType":"NETWORK_SERVICE","timestamp":2016,"transactionId":"550e8400-e29b-41d4-a716-446655440000","transactionTransmissionStates":"SENT","transactionType":"TRANSACTION_HASH"}
02-10 01:13:06.193 2817-2963/? I/System.out: Transaction Transmission gets a new message
02-10 01:13:19.415 2817-2932/? I/System.out: -----------------------
02-10 01:13:19.415 2817-2932/? I/System.out: RECEIVING BUSINESS TRANSACTION-----------------------
02-10 01:13:19.415 2817-2932/? I/System.out: -----------------------
02-10 01:13:19.421 2817-2932/? I/System.out:  STATE: SENT-----------------------
02-10 01:13:19.421 2817-2932/? I/System.out: RECEIVING BUSINESS TRANSACTION -----------------------
02-10 01:13:19.421 2817-2932/? I/System.out: -----------------------
02-10 01:13:19.466 2817-2932/? I/System.out:  STATE: SEEN_BY_OWN_NETWORK_SERVICE-----------------------
02-10 01:13:19.466 2817-2932/? I/System.out: SENDING ANSWER -----------------------
02-10 01:13:19.466 2817-2932/? I/System.out: -----------------------
02-10 01:13:20.310 2817-2964/? I/System.out:  STATE: SEEN_BY_OWN_NETWORK_SERVICEWsCommunicationVPNClient - sendMessage
02-10 01:13:21.162 2817-2884/? E/AndroidRuntime: FATAL EXCEPTION: Thread-253
                                                 Process: com.bitdubai.fermat, PID: 2817
                                                 java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bitdubai.fermat_cbp_api.layer.contract.customer_broker_sale.interfaces.CustomerBrokerContractSale.getContractId()' on a null object reference
                                                     at com.bitdubai.fermat_cbp_plugin.layer.business_transaction.customer_ack_offline_merchandise.developer.bitdubai.version_1.database.CustomerAckOfflineMerchandiseBusinessTransactionDao.buildDatabaseTableRecord(CustomerAckOfflineMerchandiseBusinessTransactionDao.java:697)
                                                     at com.bitdubai.fermat_cbp_plugin.layer.business_transaction.customer_ack_offline_merchandise.developer.bitdubai.version_1.database.CustomerAckOfflineMerchandiseBusinessTransactionDao.persistContractInDatabase(CustomerAckOfflineMerchandiseBusinessTransactionDao.java:676)
                                                     at com.bitdubai.fermat_cbp_plugin.layer.business_transaction.customer_ack_offline_merchandise.developer.bitdubai.version_1.structure.CustomerAckOfflineMerchandiseMonitorAgent$MonitorAgent.checkPendingEvent(CustomerAckOfflineMerchandiseMonitorAgent.java:369)
                                                     at com.bitdubai.fermat_cbp_plugin.layer.business_transaction.customer_ack_offline_merchandise.developer.bitdubai.version_1.structure.CustomerAckOfflineMerchandiseMonitorAgent$MonitorAgent.doTheMainTask(CustomerAckOfflineMerchandiseMonitorAgent.java:305)
                                                     at com.bitdubai.fermat_cbp_plugin.layer.business_transaction.customer_ack_offline_merchandise.developer.bitdubai.version_1.structure.CustomerAckOfflineMerchandiseMonitorAgent$MonitorAgent.run(CustomerAckOfflineMerchandiseMonitorAgent.java:199)
                                                     at java.lang.Thread.run(Thread.java:818)
02-10 01:13:21.170 748-1832/system_process W/ActivityManager:   Force finishing activity 1 com.bitdubai.fermat/com.bitdubai.android_core.app.DesktopActivity
02-10 01:13:21.203 743-743/? E/EGL_emulation: tid 743: eglCreateSyncKHR(1209): error 0x3004 (EGL_BAD_ATTRIBUTE)

**Comment by darkestpriest** [comment]
Thanks @GaboHub there is an issue with reporting this behaviour #4762

**Comment by darkestpriest** [comment]
Fixed
