### ISSUE TITLE
CBP - Business Transaction - Add externalTransactionId to BusinessTransactionRecord

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#4855]
Parents: #4843 #4844
Is required to include UUID externalTransactionId parameter in BusinessTransactionRecord class, also, this class must include getExternalTransactionId and setExternalTransactionId methods.
You must include this new parameter as class object.
PD: edit the toString method to include this new parameter.

**Comment by alexanderejm** [comment]
Issue fixed
