### ISSUE TITLE
Migrate CHT Events to CHT Api

### ISSUE THREAD

**Issue by lnacosta** [Fermat-ORG/fermat#4907]
There is events in fermat-pip belonging to CHT Platform.

**Comment by franklinmarcano1970** [comment]
@lostwood @GaboHub Revisar este caso para migrar PIP.

**Comment by lnacosta** [comment]
@lostwood @GaboHub por favor, avísenme si tienen alguna duda...

**Comment by franklinmarcano1970** [comment]
@lnacosta Todo bien leon todo claro, gracias.
