### ISSUE TITLE
CBP - Business Transaction - Broker Submit Offline Merchandise - QA - Generic Exception Managment

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#4919]
This issue is part #3968
Check the documentation (in spanish) and follow the instructions described in the following [link] (https://github.com/jorgeejgonzalez/fermat/wiki/Gestion-de-Excepciones-Genericas-en-Fermat) about *__Generic Exception Managment__* in public method in Fermat plugin.

**Comment by alexanderejm** [comment]
Issue fixed
