### ISSUE TITLE
DAP - Asset Issuer Wallet - GUI changes

### ISSUE THREAD

**Issue by javafrank** [Fermat-ORG/fermat#4942]
# Asset Issuer Wallet
- Show transactions stored from the wallet for an specific asset in the Asset Detail fragment.
- Remove actions buttons from Asset Detail fragment
- Add new Options menu that will show the following actions: Deliver Asset, Appropriate Asset

**Comment by javafrank** [comment]
@acostarodrigo please assign this issue to me.

**Comment by acostarodrigo** [comment]
Te sumo lo siguiente, para todas las wallets.
Fijate de achicar un poco la parte central, ya que tiene muchos espacios.

Con la visualización de las transacciones, necesitamos recuperar espacio para mostrarlas correctamente.

Creo que se puede sacar unos milimetros de arriba y abajo, e incluso achicar un poquito las letras.

![image](https://cloud.githubusercontent.com/assets/9518556/13182094/df4623bc-d70e-11e5-8d5c-c93145435181.png)
