### ISSUE TITLE
BCH- Crypto Network Bitcoin - Error trying to monitor the Bitcoin network

### ISSUE THREAD

**Issue by nattyco** [Fermat-ORG/fermat#4959]
Desde la Reference Wallet se cambio el Setting del Network Type a TestNet , se agrega un extra user con el address de un faucet externo (http://bitcoinfaucet.uo1.net/send.php), se obtiene un address para pedir al faucet btc.
(El error de Attempt to invoke virtual method 'void org.bitcoinj.core.PeerGroup.stop()' on a null object reference, se produjo tambien en las pruebas de envio de btc entre Intra User usando la regtest, tratando de enviar varias transacciones al mismo tiempo.)
Los btc no llegaron en el logcat se ven estos errores

========================================================================================================================================================
02-22 08:42:33.782    6643-6726/org.fermat W/System.err﹕ Fermat Error Manager * Unexpected Exception Report
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ ========================================================================================================================================================
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Source: BITDUBAI_BITCOIN_CRYPTO_NETWORK
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ ********************************************************************************************************************************************************
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Exception Number: 1
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Exception Type: class java.lang.NullPointerException
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Exception Message: Attempt to invoke virtual method 'void org.bitcoinj.core.PeerGroup.stop()' on a null object reference
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Exception Possible Cause: N/A
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Exception Context:
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ N/A
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Exception Stack Trace:
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkMonitor - Line: 131
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkManager - Line: 213
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.BitcoinCryptoNetworkPluginRoot - Line: 149
02-22 08:42:33.783    6643-6726/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.asset_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 213
02-22 08:42:33.784    6643-6726/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.asset_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 123
02-22 08:42:33.784    6643-6726/org.fermat W/System.err﹕ Class: java.lang.Thread - Line: 818
02-22 08:42:33.784    6643-6726/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 08:42:33.784    6643-6726/org.fermat W/System.err﹕ Exceptions Processed: 1
02-22 08:42:33.784    6643-6726/org.fermat W/System.err﹕ ========================================================================================================================================================

02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ Exception Number: 1
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ Exception Type: class com.bitdubai.fermat_bch_api.layer.crypto_network.bitcoin.exceptions.CantMonitorBitcoinNetworkException
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ Exception Message: There was an error trying to monitor the Bitcoin network
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ Exception Possible Cause: N/A
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ Exception Context:
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ N/A
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ Exception Stack Trace:
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.BitcoinCryptoNetworkPluginRoot - Line: 152
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.asset_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 213
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.asset_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 123
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ Class: java.lang.Thread - Line: 818
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ [ 02-22 08:42:33.786  6643: 6726 W/System.err ]
            at com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.BitcoinCryptoNetworkPluginRoot.monitorNetworkFromKeyList(BitcoinCryptoNetworkPluginRoot.java:152)
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.asset_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent.doTheMainTask(VaultKeyHierarchyMaintainer.java:213)
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.asset_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent.run(VaultKeyHierarchyMaintainer.java:123)
02-22 08:42:33.786    6643-6726/org.fermat W/System.err﹕ at java.lang.Thread.run(Thread.java:818)

========================================================================================================================================================
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Source: BITDUBAI_BITCOIN_CRYPTO_NETWORK
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ ********************************************************************************************************************************************************
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Exception Number: 1
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Exception Type: class com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.exceptions.BlockchainException
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Exception Message: There was an error in the blockchain.
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Exception Possible Cause: N/A
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Exception Context:
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Could not create blockchain to store block headers.
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Exception Stack Trace:
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkBlockChain - Line: 77
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkMonitor - Line: 156
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkMonitor - Line: 59
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkMonitor$1 - Line: 115
02-22 09:02:46.153    2367-4160/org.fermat W/System.err﹕ Class: java.lang.Thread - Line: 818

**Comment by nattyco** [comment]
Probe las ultimas correcciones y al pedir btc al faucet tanto con Regtest como con Testnet  da este error

========================================================================================================================================================
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Fermat Error Manager * Unexpected Exception Report
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ ========================================================================================================================================================
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Source: BITDUBAI_BITCOIN_CRYPTO_NETWORK
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ ********************************************************************************************************************************************************
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Exception Number: 1
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Exception Type: class java.lang.IllegalStateException
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Exception Message: Context does not match implicit network params: org.bitcoinj.params.TestNet3Params@14ccf24b vs org.bitcoinj.params.RegTestParams@2b55c76b
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Exception Possible Cause: N/A
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Exception Context:
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ N/A
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Exception Stack Trace:
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Class: org.bitcoinj.core.Context - Line: 102
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Class: org.bitcoinj.core.PeerGroup - Line: 269
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkMonitor$MonitorAgent - Line: 238
02-23 09:14:51.813   9360-18521/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkMonitor$MonitorAgent - Line: 214

**Comment by acostarodrigo** [comment]
el fix ya está en mi repo, branch develop.
Probalo y avisame por favor.
