### ISSUE TITLE
CBP - Reference Wallet - Crypto Broker - GUI - Closed Negotiation Details Activity

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#4961]
Implementación de la actividad Closed Negotiation Details que permite a un broker ver los detalles de una negociación cerrada.
- Esta información no se puede editar. 
- Esta actividad es accesible desde la pantalla de Open Contract Details (desde le home) y Closed Contract Details (desde Contract History)
- El diseño estará basado en el Open Negotiation Details Activity (Fermat-ORG/fermat-graphic-design#272) solo que no se mostraran los botones de CONFIRM, SEND, ADD NOTE y CANCEL NEGOTIATION

**Comment by franklinmarcano1970** [comment]
@Lozadaa Revisa:
Agregue unos TODO en los fragmentos ContractDetailActivityFragment (linea 163) y CloseContractDetailsFragment (linea 132) para que los revisen.

    Hace falta quitar el menú del action bar
    Hacer que las tarjetas no muestren el botón de confirmar. Eso se hace en el adapter, en el método bindHolder(...)
    El botón Send y Add Note. Eso se hace en el adapter, quitando el FooterViewHolder
    Quitar todos los listeners que tiene actualmente el adapter
    el Card de Exchange Rate se le debe quitar la sección Suggested y la sección Market Exchange Rate

El principal problema con esta pantalla era el método getNegotiationInformation(...) del module para obtener la información de la negociación, que no estaba del todo implementado y le faltaba un mejor manejo de excepciones.

Aparte de eso aquí esta varios detalles que encontré:

    En ClosedNegotiationDetailsFragment se estaba haciendo referencia a un Button btn_confirm que no esta en el layout cbw_fragment_closed_negotiation_details_activity
    En ContractDetailsActivityFragment no se estaba consumiendo el método getNegotiationInformation(...) y estabas pasando a través de la session el objeto ContractBasicInformation
    En ContractDetailsActivityFragment se estaba cambiando a la actividad
    Se agregó una actividad innecesaria en WalletRuntimeEnginePluginRoot (la actividad es: Activities.CBP_CRYPTO_BROKER_WALLET_CLOSE_NEGOTIATION_DETAILS). Para eso ya existe la actividad Activities.CBP_CRYPTO_BROKER_WALLET_CLOSE_NEGOTIATION_DETAILS_OPEN_CONTRACT
