### ISSUE TITLE
P2P: Install and Configure Jmeter Library

### ISSUE THREAD

**Issue by hendry19901990** [Fermat-ORG/fermat#4994]
Parent #4992

Install and Configure Jmeter Library to test the Cloud Server

Please assign to me, @Rart3001

**Comment by hendry19901990** [comment]
Jmeter Library already is Installed and Configured successfully

**Comment by furszy** [comment]
Perfecto!

**Comment by hendry19901990** [comment]
Please proceed to close this issue, the manual of Installation and Configuration is done
