### ISSUE TITLE
CHT - Wrong Local Public key

### ISSUE THREAD

**Issue by GaboHub** [Fermat-ORG/fermat#5001]
When you send a message it takes the network service public key as local public key, it sends it right but when the user tries to response, the message won't get to the wanted contact, because when we response the message we get the remote public key from the saved contact at this time and the message was sent by the network service public key what happends to be a different one.

@darkestpriest

**Comment by darkestpriest** [comment]
This was fixed in #4986.
The main problem was the platformComponentType, when you answer to an unregistered contact, the public key to respond is the network service public key, but the platformComponentType was registered from the actor. Now we set the platformComponentType is NetworkService.
