### ISSUE TITLE
CHT-Android-Improve wallpaper image

### ISSUE THREAD

**Issue by RoyGF** [Fermat-ORG/fermat#5122]
- [ ] Modify the wallpaper because that doesn't reduces
- [ ] change the image

Assigned to @Lozadaa  @josejcb 
@franklinmarcano1970

**Comment by josejcb** [comment]
@franklinmarcano1970  Please, check this again @Lozadaa

**Comment by franklinmarcano1970** [comment]
@Lozadaa @josejcb Richard por favor dale prioridad a esto tiene que estar cerrado para hoy ya que hoy se cierra el Sprint...

**Comment by josejcb** [comment]
Closed

**Comment by Lozadaa** [comment]
Fix. This issue was solved by  @josejcb
