### ISSUE TITLE
BCH - CryptoNetwork - Implement method to get Download progress of the blockchain

### ISSUE THREAD

**Issue by acostarodrigo** [Fermat-ORG/fermat#5237]
# Download Progress notification

- [x] create function BlockchainDownloadProgress getBlockchainDownloadProgress(BlockchainNetworkType blockchainNetworkType)
- [x] implement class BlockchainDownloadProgress
- [ ] implement function BlockchainDownloadProgress getBlockchainDownloadProgress(BlockchainNetworkType blockchainNetworkType)

@furszy comentá por favor el objeto android a utilizar así se lo paso a mis equipos.
Cuando esté fully implemented, notifico. Pero ya está la interfaz para utilizarlo en CrypoNetwork

**Comment by furszy** [comment]
@acostarodrigo acá estoy, perdón que no lo lei antes. 
Tienen un tipo de notificacion el cual te permite ir incrementando una progress bar en la barra superior de la pantalla. Para esto se puede notiificar desde un plugin de la plataforma con el broadcaster o desde un plugin de android con un manager de notificaciones.
Mandenme un mensaje y les mando un snippet de código para ambos casos.

**Comment by acostarodrigo** [comment]
cc @nattyco
