### ISSUE TITLE
BCH- Crypto Vault Manager Error 

### ISSUE THREAD

**Issue by nattyco** [Fermat-ORG/fermat#5241]
Tengo tres payments request por disintos montos, 7 btc, 3 btc y 500 satoshis, los apruebo a los tres y se ve este error en la CryptoVault.
Tengo 43 btc de balance en la wallet.

03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Source: BITDUBAI_CCP_OUTGOING_INTRA_ACTOR_TRANSACTION
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ ********************************************************************************************************************************************************
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Exception Number: 1
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Exception Type: class org.bitcoinj.core.Wallet$DustySendRequested
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Exception Message: null
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Exception Possible Cause: N/A
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Exception Context:
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ N/A
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Exception Stack Trace:
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Class: org.bitcoinj.core.Wallet - Line: 3638
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.BitcoinCurrencyCryptoVaultManager - Line: 406
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.CryptoVaultBitcoinCurrencyPluginRoot - Line: 269
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.CryptoVaultBitcoinCurrencyPluginRoot - Line: 250
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_ccp_plugin.layer.crypto_transaction.outgoing_intra_actor.developer.bitdubai.version_1.structure.OutgoingIntraActorTransactionProcessorAgent$TransactionProcessorAgent - Line: 286
03-09 12:45:30.981    1537-1624/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_ccp_plugin.layer.crypto_transaction.outgoing_intra_actor.developer.bitdubai.version_1.structure.OutgoingIntraActorTransactionProcessorAgent$TransactionProcessorAgent - Line: 226

**Comment by acostarodrigo** [comment]
Existe una limitacion al monto mínimo de satoshis que podemos enviar.
En teoria podríamos enviar un satoshi, pero para reducir el spam de transacciones, se limitó en los clientes el mínimo de satoshis a enviar.

Yo voy a agregar el valor mínimo aceptable en la API de BCH para que esté accesible para las wallets y hagan la validación correspondiente.

@furszy @nindriago

**Comment by acostarodrigo** [comment]
el valor estará seteado en un poco mas de 500 satoshis

**Comment by acostarodrigo** [comment]
de mi repo pueden tomar el valor BitcoinNetworkConfiguration.MIN_ALLOWED_SATOSHIS_ON_SEND

o utilizar de la clase abstracta el método estatico CryptoVault.isDustySend que les dice si es un valor "dusty" es decir que no va a ser aceptado por la red o no.

@nindriago esta validación la tenemos que incluir en la transacción de Compra Venta de Assets, cuando el Seller especifica el monto del asset a vender, no debe ser menor a lo permitido. Incluir en el module de la user Wallet y reportar correctamente la notificacion por pantalla.
