### ISSUE TITLE
CCP- Reference Wallet Implemet Validation MIN_ALLOWED_SATOSHIS_ON_SEND

### ISSUE THREAD

**Issue by nattyco** [Fermat-ORG/fermat#5266]
Existe una limitacion al monto mínimo de satoshis que podemos enviar.
En teoria podríamos enviar un satoshi, pero para reducir el spam de transacciones, se limitó en los clientes el mínimo de satoshis a enviar. (en la Crypto Network)

Implementar el los forms de envio de Btc y envio de Payment Request la verificacion de que el monto a enviar supere el minimo configurado. Utilizando la configuracion BitcoinNetworkConfiguration.MIN_ALLOWED_SATOSHIS_ON_SEND que se agrego a la Api de la capa BCH.

Tambien dejar por defecto en los formularios de envio que los valores se cargan como BTC y no como bits.

**Comment by acostarodrigo** [comment]
@nattyco  no me lo asignes a mi

**Comment by nattyco** [comment]
@acostarodrigo perdon, no se porque se asigno a vos, aprete tu nombre sin querer.
