### ISSUE TITLE
CHT-Community-UI/UX-App Design

### ISSUE THREAD

**Issue by josejcb** [Fermat-ORG/fermat#5371]
- [ ] to create an icon for the community
- [ ] to design views for the community
@franklinmarcano1970 @arnaldos

**Comment by josejcb** [comment]
Saludos, aca los mockups para la community. @arnaldos @franklinmarcano1970 @Lozadaa 
[Chat Community add contact.zip](https://github.com/Fermat-ORG/fermat/files/196780/Chat.Community.add.contact.zip)
[mock link](https://ninjamock.com/s/TSDDS)

**Comment by arnaldos** [comment]
@josejcb @Lozadaa @franklinmarcano1970 for this issue we work this wireframes a week ago https://github.com/Fermat-ORG/fermat-graphic-design/issues/719
