### ISSUE TITLE
CHT-Identities-UI/UX-App Design

### ISSUE THREAD

**Issue by josejcb** [Fermat-ORG/fermat#5373]
- [ ] to create an icon for the Identities subapp
- [ ] to design views for the Identities subapp 
@franklinmarcano1970 @arnaldos @Lozadaa

**Comment by Lozadaa** [comment]
Here are the stipulated mockups for the Identities Sub App:

![identities](https://cloud.githubusercontent.com/assets/9525399/14159441/bb85b4dc-f69f-11e5-905b-02ef0e34913a.png)
![dialog](https://cloud.githubusercontent.com/assets/9525399/14159442/bb8b3812-f69f-11e5-9316-a49e04600556.png)
[Identities sub app.pdf](https://github.com/Fermat-ORG/fermat/files/196531/Identities.sub.app.pdf)

@josejcb @arnaldos @franklinmarcano1970

**Comment by arnaldos** [comment]
@josejcb @Lozadaa @franklinmarcano1970 for this issue we work this wireframes a week ago https://github.com/Fermat-ORG/fermat-graphic-design/issues/720

**Comment by josejcb** [comment]
Yeah, it's ok, there is no changes, just the splash that it will be shown when the identity app is open. [Fermat-ORG/fermat-graphic-design#720](https://github.com/Fermat-ORG/fermat-graphic-design/issues/720)
