### ISSUE TITLE
App - Improve loading dialog

### ISSUE THREAD

**Issue by furszy** [Fermat-ORG/fermat#5727]
At this moment we have the infrastructure and a very basic loading view for Fermat, we have to improve the visual aspect of it.

@ivonnesantos  please upload the .gif images of the loading in this issue to see what we got today.

**Comment by furszy** [comment]
@arnaldos @m471c4 @emmysm please be part of this issue. We have to build the best loading ever.

**Comment by ivonnesantos** [comment]
@furszy eso es esto mismo https://github.com/Fermat-ORG/fermat-graphic-design/issues/549

**Comment by furszy** [comment]
Si Ivonne es el mismo. Ahora hay que mejorar esto.

**Comment by furszy** [comment]
@clp3z @ivonnesantos @arnaldos por favor empiecen con esto.

**Comment by arnaldos** [comment]
@furszy ya @ivonnesantos esta trabajando el loading en este caso  https://github.com/Fermat-ORG/fermat-graphic-design/issues/549

**Comment by ivonnesantos** [comment]
![loanding_p1](https://cloud.githubusercontent.com/assets/15238660/14338256/548240f2-fc3f-11e5-824e-5aad2332ebba.gif)

**Comment by ivonnesantos** [comment]
![loanding_p2](https://cloud.githubusercontent.com/assets/15238660/14338287/9c25539a-fc3f-11e5-8cec-fd4f7ce8dda8.gif)

Propuesta 2

**Comment by ivonnesantos** [comment]
![loanding_p2](https://cloud.githubusercontent.com/assets/15238660/14338394/b86c17cc-fc40-11e5-98d5-520aa554bf8d.gif)

Propuesta 2

**Comment by ivonnesantos** [comment]
![loanding_p3](https://cloud.githubusercontent.com/assets/15238660/14338410/d958960e-fc40-11e5-8e6c-8381adb2a965.gif)

Propuesta 3 (el mas pesado pesa 151kb)

**Comment by furszy** [comment]
La primera si, pero yo te decia que armes el entorno donde va a estar también, esta pantalla va a estar, si va a estar dentro de un popup, flotando en el aire, en una pantalla completa, encima de la pantalla que por detrás se está actualizando, etc.
Necesitamos Ivonne el loading completo con la animación.

**Comment by furszy** [comment]
@luis-fernando-molina

**Comment by Yayotron** [comment]
Estas 3 propuestas son para diálogos de carga indefinidos, deberíamos también pensar y hacer uno para una carga definida (que sepamos el tiempo que tardará, un % de una actividad que se esté completando, etc.).

**Comment by furszy** [comment]
@Yayotron estas son para carga de pantallas (salta de una pantalla a otra dentro de una app), es hacer uno genérico y armar la estructura para que cada app pueda customizar el suyo.
Hay uno con progress definido en el toolbox si te interesa usarlo.

**Comment by ivonnesantos** [comment]
![mockups](https://cloud.githubusercontent.com/assets/15238660/14391335/27b4eca4-fd85-11e5-9056-f661bd7ad84f.gif)

@furszy @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
me parece esta bueno y tiene buen tamaño para la pantalla !

**Comment by Luis-Fernando-Molina** [comment]
el ultimo esta bien, lo que esta abajo de la transparencia debe ser el desktop que cada quien tenga en su telefono.

**Comment by ivonnesantos** [comment]
![mockups](https://cloud.githubusercontent.com/assets/15238660/14396393/14faedfe-fda1-11e5-9f3a-ce9d08796736.gif)
simulando el desktop del usuario como indica @Luis-Fernando-Molina

**Comment by furszy** [comment]
@clp3z armalo en código o fijate como implementar la funcionalidad de ese gif, lo necesitamos para el viernes a más tardar por favor.

**Comment by furszy** [comment]
@clp3z Estamos esperando por lo tuyo..., necesitamos eso.

**Comment by furszy** [comment]
@clp3z como fue esto que dijiste que iba a estar para hace 2 semanas?

**Comment by clp3z** [comment]
Buenas tardes. 

Como te comenté el día viernes, ya terminé el desarrollo de ésta vista. Pero al probarla en dispositivos con distinta resolución, noté que los objetos de la animación se desplazan y estoy trabajando en eso.

Apenas termine de mejorar esos detalles, la subo al repositorio.

**Comment by clp3z** [comment]
Este issue ya fue completado. Debería ser cerrado.
