### ISSUE TITLE
P2P - Websocket CantEstablishConnectionException

### ISSUE THREAD

**Issue by nattyco** [Fermat-ORG/fermat#5813]
Sometimes when using the Sub App Community in the log is this error:

=======================================================================================================================================================
04-06 11:19:38.027  21165-21223/org.fermat.alpha W/System.err﹕ Fermat Error Manager * Unexpected Exception Report
04-06 11:19:38.027  21165-21223/org.fermat.alpha W/System.err﹕ ========================================================================================================================================================
04-06 11:19:38.027  21165-21223/org.fermat.alpha W/System.err﹕ Source: BITDUBAI_INTRAUSER_NETWORK_SERVICE
04-06 11:19:38.027  21165-21223/org.fermat.alpha W/System.err﹕ Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
04-06 11:19:38.027  21165-21223/org.fermat.alpha W/System.err﹕ ********************************************************************************************************************************************************
04-06 11:19:38.027  21165-21223/org.fermat.alpha W/System.err﹕ Exception Number: 1
04-06 11:19:38.030  21165-21223/org.fermat.alpha W/System.err﹕ Exception Type: class com.bitdubai.fermat_p2p_api.layer.p2p_communication.commons.exceptions.CantEstablishConnectionException
04-06 11:19:38.030  21165-21223/org.fermat.alpha W/System.err﹕ Exception Message: CAN'T ESTABLISH THE CONNECTION
04-06 11:19:38.030  21165-21223/org.fermat.alpha W/System.err﹕ Exception Possible Cause: Attempt to invoke interface method 'boolean javax.websocket.Session.isOpen()' on a null object reference
04-06 11:19:38.030  21165-21223/org.fermat.alpha W/System.err﹕ Exception Context:
04-06 11:19:38.031  21165-21223/org.fermat.alpha W/System.err﹕ ---------------------------------------------------------------------------------
04-06 11:19:38.031  21165-21223/org.fermat.alpha W/System.err﹕ Attempt to invoke interface method 'boolean javax.websocket.Session.isOpen()' on a null object reference
04-06 11:19:38.031  21165-21223/org.fermat.alpha W/System.err﹕ ---------------------------------------------------------------------------------
04-06 11:19:38.031  21165-21223/org.fermat.alpha W/System.err﹕ Exception Stack Trace:
04-06 11:19:38.031  21165-21223/org.fermat.alpha W/System.err﹕ ---------------------------------------------------------------------------------
04-06 11:19:38.031  21165-21223/org.fermat.alpha W/System.err﹕ Class: com.bitdubai.fermat_p2p_plugin.layer.ws.communications.cloud.client.developer.bitdubai.version_1.structure.tyrus.WsCommunicationsTyrusCloudClientConnection - Line: 956
04-06 11:19:38.031  21165-21223/org.fermat.alpha W/System.err﹕ Class: com.bitdubai.fermat_p2p_api.layer.all_definition.communication.network_services.base.CommunicationNetworkServiceConnectionManager - Line: 103
04-06 11:19:38.031  21165-21223/org.fermat.alpha W/System.err﹕ Class: com.bitdubai.fermat_p2p_api.layer.all_definition.communication.network_services.base.AbstractNetworkServiceBase - Line: 893
04-06 11:19:38.031  21165-21223/org.fermat.alpha W/System.err﹕ Class: com.bitdubai.fermat_ccp_plugin.layer.network_service.intra_user.developer.bitdubai.version_1.IntraActorNetworkServicePluginRoot$1 - Line: 386

**Comment by Rart3001** [comment]
In the class WsCommunicationsTyrusCloudClientConnection.java  before calling the method of sending messages  through the websocket it is being validated if the session that represents this open with the following code:

     if (wsCommunicationsTyrusCloudClientChannel.getClientConnection().isOpen()){
                /*
                 * Send the encode packet to the server
                 */
                wsCommunicationsTyrusCloudClientChannel.sendMessage(FermatPacketEncoder.encode(fermatPacketRespond));

            }else{
                wsCommunicationsTyrusCloudClientChannel.raiseClientConnectionLooseNotificationEvent();
                throw new Exception("Client Connection is Close");
            }

needs to be replaced if the condition of the following code:

    if(isConnected())

this must be changed on all sides that perform validation.

**Comment by hendry19901990** [comment]
Please @Rart3001  proceed to close, it already is implemented the condition
