### ISSUE TITLE
CHT-Super Issue-Difusion List Creation

### ISSUE THREAD

**Issue by RoyGF** [Fermat-ORG/fermat#5814]
Difusion List Creation (Broadcasting) of messages to added contacts on CHT.

This is a super issue and it must be labeled as super issue. It can be closed once all the children issues are closed as well. 

Assigned to @eorono @franklinmarcano1970 @Lozadaa 

@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@Lozadaa  Hacen commit en este issuer
