### ISSUE TITLE
CHT-Plugin-Difusion List Creation

### ISSUE THREAD

**Issue by RoyGF** [Fermat-ORG/fermat#5818]
This issue is related to super issue #5814

Difusion List Creation (Boradcasting) of messages to added contacts on CHT

- [ ]  Make a wizard for: step-1 name the list. Step-2 select the connections (contacts) to whom the messages are sent.
- [ ]  Must be able to edit the redifusion's name
- [ ]  Must be able to add the chat history
- [ ]  Must be able to send message to every selected connection
- [ ]  Watch message on every connection by individual form and answer to the redifusion emisor

Assigned to @eorono @Lozadaa @franklinmarcano1970

@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@eorono Hacen commit en este issuer
