### ISSUE TITLE
CHT-NS-Group Messages Sending

### ISSUE THREAD

**Issue by RoyGF** [Fermat-ORG/fermat#5823]
This issue is related to super issue #5822

Show a label just under the name of the group alongside the remote actor alias that is writing a message
Send messages throught the NS remote public key with the message that the group wrote.
Storage all message in history messages from the group chat.

Assigned to @franklinmarcano1970 @josejcb @JDVilchez 

@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@josejcb @JDVilchez Hacen commit en este issuer
