### ISSUE TITLE
CHT-Super Issue-Watch when the remote is writing

### ISSUE THREAD

**Issue by RoyGF** [Fermat-ORG/fermat#5828]
This allows when the remote is writing a message, providing a much better interaction with Chat

This issue is a super issue and it must be labeled as super issue. It can be closed once all the children issues are closed as well.

Assigned to @JDVilchez @Lozadaa 

@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@Lozadaa Hace commit en este issuer.
