### ISSUE TITLE
CHT-NS-Watch When the Remote is Writing

### ISSUE THREAD

**Issue by RoyGF** [Fermat-ORG/fermat#5829]
This issue is related to super issue #5828

Make a label called "... is writing" that shows when the remote is writing a message
Must be able to send through NS Actor Connection the flag when a messages is being written on Chat to remote actor involved

Assiged to @JDVilchez @Lozadaa 

@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@Lozadaa Haces commit en este issuer
