### ISSUE TITLE
CHT-Actor Connection-Show Last Connection from the Remote

### ISSUE THREAD

**Issue by RoyGF** [Fermat-ORG/fermat#5836]
This issue is related to super issue #5833

Show a label, just under the name alognside a text that contains the last connection from the latter when the Remote is offline
Being able to save Remote's last connection on AC
Being able to send throught NS last time the Remote Actor was online

Assigned to @JDVilchez @Lozadaa 

@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@Lozadaa Hace commit en este issuer
