### ISSUE TITLE
CHT-Middleware-Show When the Remote is Online

### ISSUE THREAD

**Issue by RoyGF** [Fermat-ORG/fermat#5839]
This issue is related to super issue #5837 

- [ ] Show a label just under the remote name with the text "online" when the remote is online
- [ ] Being able to send through NS Actor Connection a flag when the remote is online

Assigned to @JDVilchez @Lozadaa 

@franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
@Lozadaa Hace commit en este issuer
