### ISSUE TITLE
CHT-Plugin-Delete an Specific Chat

### ISSUE THREAD

**Issue by RoyGF** [Fermat-ORG/fermat#5855]
This issue is related to super issue #5852 

- [ ] Being able to delete all messages in the specific chat from chat list and from the messages seen in the proper chat

Assigned to @josejcb 

@franklinmarcano1970

**Comment by josejcb** [comment]
fixed in #5673 @RoyGF close it

**Comment by josejcb** [comment]
repeated #5673
