### ISSUE TITLE
TKY - Reference Wallet - Remove all the drawable unused

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#5975]
Is required to check if exists any drawable unused in the res.drawable package to decrease the compilation time and clean the repository.

Also, is required to check if any drawable has a size up to 20Kb, in that case, must be replaced for another resource with a minor size.

Plus, check all the layout, if exists a layout unused, please, remove from repository.

**Comment by lostwood** [comment]
close #5975
