### ISSUE TITLE
CCP-Loss Protected Wallet - Apply new design patterns to different layouts

### ISSUE THREAD

**Issue by Exilum** [Fermat-ORG/fermat#6078]
- [ ] Apply new design patter to contact list layout
- [ ] Apply new design patter to contact detail layout
- [ ] Apply new design patter to Transaction sent and received layouts
- [ ] Apply new design patter to Request sent and received layouts
- [ ] Apply new design patter to contact list void layout

**Comment by Exilum** [comment]
@nattyco please assign this issue to me.

**Comment by nattyco** [comment]
Complete
