### ISSUE TITLE
ART/TKY - Sub App - Artist/Fan Identity - Information displayed to User

### ISSUE THREAD

**Issue by alexanderejm** [Fermat-ORG/fermat#6140]
it is required that all text displayed to the user in ART and TKY identitys to be in english.

it should be in english unlike this:
![screenshot from 2016-05-04 14 33 05](https://cloud.githubusercontent.com/assets/16577032/15025874/3e0ee9fc-1205-11e6-88de-28e79af51037.png)

**Comment by darkestpriest** [comment]
Fixed
