### ISSUE TITLE
ART - Sub app - Artist/Fan Community cancel connection bug

### ISSUE THREAD

**Issue by alexanderejm** [Fermat-ORG/fermat#6145]
given the following circumstance:

Actor A sends invitation to Actor B while staying on the same screen.
Actor B accepts invitation.
Actor A cancels invitation.

![screenshot from 2016-05-05 12 53 19](https://cloud.githubusercontent.com/assets/16577032/15051135/fea06d92-12c0-11e6-9d85-f6fd4290e9d2.png)

the following Exception is captured, please fix this:
`05-05 12:38:25.592 5874-5874/org.fermat W/System.err: ========================================================================================================================================================
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Fermat Error Manager * Unexpected Exception Report
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: ========================================================================================================================================================
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Source: PluginVersionReference{pluginDeveloperReference=PluginDeveloperReference{pluginReference=PluginReference{layerReference=LayerReference{platformReference=PlatformReference{, platform=ART_PLATFORM}, layer=ACTOR_CONNECTION}, plugin=ARTIST_ACTOR_CONNECTION}, developer=BITDUBAI}, version=1.0.0}
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: ********************************************************************************************************************************************************
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Exception Number: 1
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Exception Type: class com.bitdubai.fermat_api.layer.actor_connection.common.exceptions.CantGetConnectionStateException
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Exception Message: CAN'T GET CONNECTION STATE EXCEPTION
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Exception Possible Cause: The connectionId is required, can not be null
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Exception Context: 
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: N/A
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Exception Stack Trace: 
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: com.bitdubai.fermat_api.layer.actor_connection.common.database_abstract_classes.ActorConnectionDao - Line: 259
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.actor_connection.artist.developer.bitdubai.version_1.structure.ActorConnectionManager - Line: 385
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.sub_app_module.artist_community.developer.bitdubai.version_1.structure.ArtistCommunityManager - Line: 315
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: com.bitdubai.sub_app_artist_community.commons.popups.CancelDialog - Line: 107
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: android.view.View - Line: 5198
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: android.view.View$PerformClick - Line: 21147
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: android.os.Handler - Line: 739
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: android.os.Handler - Line: 95
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: android.os.Looper - Line: 148
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: android.app.ActivityThread - Line: 5417
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: -2
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit$MethodAndArgsCaller - Line: 726
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit - Line: 616
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: Exceptions Processed: 1
05-05 12:38:25.593 5874-5874/org.fermat W/System.err: ========================================================================================================================================================
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ========================================================================================================================================================
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Fermat Error Manager * Unexpected Exception Report
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ========================================================================================================================================================
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Source: PluginVersionReference{pluginDeveloperReference=PluginDeveloperReference{pluginReference=PluginReference{layerReference=LayerReference{platformReference=PlatformReference{, platform=ART_PLATFORM}, layer=SUB_APP_MODULE}, plugin=ARTIST_COMMUNITY_SUB_APP_MODULE}, developer=BITDUBAI}, version=1.0.0}
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ********************************************************************************************************************************************************
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Number: 1
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Type: class com.bitdubai.fermat_api.layer.actor_connection.common.exceptions.CantGetConnectionStateException
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Message: CAN'T GET CONNECTION STATE EXCEPTION
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Possible Cause: The connectionId is required, can not be null
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Context: 
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: N/A
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Stack Trace: 
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.bitdubai.fermat_api.layer.actor_connection.common.database_abstract_classes.ActorConnectionDao - Line: 259
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.actor_connection.artist.developer.bitdubai.version_1.structure.ActorConnectionManager - Line: 385
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.sub_app_module.artist_community.developer.bitdubai.version_1.structure.ArtistCommunityManager - Line: 315
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.bitdubai.sub_app_artist_community.commons.popups.CancelDialog - Line: 107
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.view.View - Line: 5198
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.view.View$PerformClick - Line: 21147
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.os.Handler - Line: 739
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.os.Handler - Line: 95
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.os.Looper - Line: 148
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.app.ActivityThread - Line: 5417
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: -2
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit$MethodAndArgsCaller - Line: 726
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit - Line: 616
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ********************************************************************************************************************************************************
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Number: 1
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Type: class com.bitdubai.fermat_api.layer.actor_connection.common.exceptions.CantGetConnectionStateException
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Message: CAN'T GET CONNECTION STATE EXCEPTION
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Possible Cause: The connectionId is required, can not be null
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Context: 
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: N/A
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Stack Trace: 
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.bitdubai.fermat_api.layer.actor_connection.common.database_abstract_classes.ActorConnectionDao - Line: 259
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.actor_connection.artist.developer.bitdubai.version_1.structure.ActorConnectionManager - Line: 385
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.sub_app_module.artist_community.developer.bitdubai.version_1.structure.ArtistCommunityManager - Line: 315
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.bitdubai.sub_app_artist_community.commons.popups.CancelDialog - Line: 107
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.view.View - Line: 5198
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.view.View$PerformClick - Line: 21147
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.os.Handler - Line: 739
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.os.Handler - Line: 95
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.os.Looper - Line: 148
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: android.app.ActivityThread - Line: 5417
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: -2
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit$MethodAndArgsCaller - Line: 726
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit - Line: 616
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Number: 2
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Type: class com.bitdubai.fermat_api.layer.actor_connection.common.exceptions.CantCancelActorConnectionRequestException
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Message: CAN'T CANCEL ACTOR CONNECTION REQUEST EXCEPTION
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Possible Cause: Error trying to get the connection state.
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exception Context: 
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: connectionId: null
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: Exceptions Processed: 2
05-05 12:38:25.601 5874-5874/org.fermat W/System.err: `========================================================================================================================================================`

**Comment by darkestpriest** [comment]
I think with a proper handling exception we can avoid this behaviour, I'll check this, thanks @alexanderejm

**Comment by GaboHub** [comment]
Will check this right away.
