### ISSUE TITLE
Art - Sub app - Artist Community - Selec an Actor bug

### ISSUE THREAD

**Issue by alexanderejm** [Fermat-ORG/fermat#6158]
when selecting for the first time an actor wich previously accepted a connection, the application crashes an the following exception is catch:

`05-06 17:29:55.674 1518-1518/org.fermat W/System.err: ========================================================================================================================================================
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Fermat Error Manager * Unexpected Exception Report
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: ========================================================================================================================================================
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Source: ACTIVITY
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Severity: UNSTABLE
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: ********************************************************************************************************************************************************
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Exception Number: 1
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Exception Type: class java.lang.IllegalArgumentException
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Exception Message: Error in changeActivity
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Exception Possible Cause: N/A
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Exception Context: 
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: N/A
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Exception Stack Trace: 
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: com.bitdubai.android_core.app.AppActivity - Line: 359
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: com.bitdubai.fermat_android_api.layer.definition.wallet.AbstractFermatFragment - Line: 206
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: com.bitdubai.sub_app_artist_community.fragments.ConnectionsWorldFragment - Line: 319
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: com.bitdubai.sub_app_artist_community.fragments.ConnectionsWorldFragment - Line: 53
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: com.bitdubai.fermat_android_api.ui.adapters.FermatAdapter$1 - Line: 50
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: android.view.View - Line: 5198
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: android.view.View$PerformClick - Line: 21147
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: android.os.Handler - Line: 739
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: android.os.Handler - Line: 95
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: android.os.Looper - Line: 148
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: android.app.ActivityThread - Line: 5417
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: -2
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit$MethodAndArgsCaller - Line: 726
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit - Line: 616
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: Exceptions Processed: 1
05-06 17:29:55.674 1518-1518/org.fermat W/System.err: ========================================================================================================================================================
05-06 17:29:55.676 1518-1518/org.fermat W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at com.bitdubai.android_core.app.AppActivity.changeActivity(AppActivity.java:344)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at com.bitdubai.fermat_android_api.layer.definition.wallet.AbstractFermatFragment.changeActivity(AbstractFermatFragment.java:206)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at com.bitdubai.sub_app_artist_community.fragments.ConnectionsWorldFragment.onItemClickListener(ConnectionsWorldFragment.java:319)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at com.bitdubai.sub_app_artist_community.fragments.ConnectionsWorldFragment.onItemClickListener(ConnectionsWorldFragment.java:53)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at com.bitdubai.fermat_android_api.ui.adapters.FermatAdapter$1.onClick(FermatAdapter.java:50)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at android.view.View.performClick(View.java:5198)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at android.view.View$PerformClick.run(View.java:21147)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-06 17:29:55.676 1518-1518/org.fermat W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by darkestpriest** [comment]
Fixed
