### ISSUE TITLE
Art - Sub app - Artist Community - Notification bug

### ISSUE THREAD

**Issue by alexanderejm** [Fermat-ORG/fermat#6168]
Under the following circumstance:
1)Actor A sent's a connection request to actor B
2)Actor A returns to main sub app artist community screen
3)Actor B accepts connection request
4)when actor A recieve notification from actor B of an accepted connection, actor A enters connection tab in the navigation drawer.

the fermat aplication will reset and the next exception catch:
`05-09 22:11:31.346 14212-14212/org.fermat W/System.err: ========================================================================================================================================================
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Fermat Error Manager * Unexpected Exception Report
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: ========================================================================================================================================================
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Source: ACTIVITY
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Severity: UNSTABLE
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: ********************************************************************************************************************************************************
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Exception Number: 1
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Exception Type: class java.lang.IllegalArgumentException
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Exception Message: Error in changeActivity
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Exception Possible Cause: N/A
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Exception Context: 
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: N/A
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Exception Stack Trace: 
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Class: com.bitdubai.android_core.app.AppActivity - Line: 359
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Class: com.bitdubai.android_core.app.AppActivity - Line: 481
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Class: com.bitdubai.android_core.app.FermatActivity$12 - Line: 1648
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Class: android.os.Handler - Line: 739
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Class: android.os.Handler - Line: 95
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Class: android.os.Looper - Line: 148
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Class: android.app.ActivityThread - Line: 5417
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: -2
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit$MethodAndArgsCaller - Line: 726
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit - Line: 616
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: Exceptions Processed: 1
05-09 22:11:31.346 14212-14212/org.fermat W/System.err: ========================================================================================================================================================
05-09 22:11:31.373 14212-14212/org.fermat W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
05-09 22:11:31.373 14212-14212/org.fermat W/System.err:     at com.bitdubai.android_core.app.AppActivity.changeActivity(AppActivity.java:344)
05-09 22:11:31.374 14212-14212/org.fermat W/System.err:     at com.bitdubai.android_core.app.AppActivity.onNavigationMenuItemTouchListener(AppActivity.java:481)
05-09 22:11:31.374 14212-14212/org.fermat W/System.err:     at com.bitdubai.android_core.app.FermatActivity$12.run(FermatActivity.java:1648)
05-09 22:11:31.374 14212-14212/org.fermat W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-09 22:11:31.374 14212-14212/org.fermat W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-09 22:11:31.374 14212-14212/org.fermat W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-09 22:11:31.374 14212-14212/org.fermat W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
05-09 22:11:31.374 14212-14212/org.fermat W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-09 22:11:31.374 14212-14212/org.fermat W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-09 22:11:31.374 14212-14212/org.fermat W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by darkestpriest** [comment]
This is the same exception reported in #6158, please, take a look.

**Comment by darkestpriest** [comment]
Fixed
