### ISSUE TITLE
ART - ExposingData class - Cast Excepcion

### ISSUE THREAD

**Issue by GaboHub** [Fermat-ORG/fermat#6170]
Currently working on my updates to the identities i have found the following excepcion:

05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Source: AbstractEvent{eventType=ART_ACTOR_NETWORK_SERVICE_CONNECTION_LOST, eventSource=ACTOR_NETWORK_SERVICE_ARTIST}
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Severity: Unknow
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: ********************************************************************************************************************************************************
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Exception Number: 1
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Exception Type: class java.lang.ClassCastException
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Exception Message: com.bitdubai.fermat_art_api.layer.actor_network_service.interfaces.artist.util.ArtistExternalPlatformInformation cannot be cast to java.util.HashMap
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Exception Possible Cause: N/A
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Exception Context: 
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: N/A
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Exception Stack Trace: 
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Class: com.bitdubai.fermat_art_api.layer.actor_network_service.interfaces.artist.util.ArtistExposingData - Line: 33
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.identity.artist.developer.bitdubai.version_1.ArtistIdentityPluginRoot - Line: 155
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.identity.artist.developer.bitdubai.version_1.event_handler.ArtistConnectionLostEventHandler - Line: 28
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Class: com.bitdubai.fermat_api.layer.all_definition.events.common.GenericEventListener - Line: 49
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Class: com.bitdubai.fermat_pip_addon.layer.platform_service.event_manager.developer.bitdubai.version_1.structure.EventManagerPlatformServiceManager$1 - Line: 113
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Class: java.util.concurrent.Executors$RunnableAdapter - Line: 422
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Class: java.util.concurrent.FutureTask - Line: 237
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Class: java.util.concurrent.ThreadPoolExecutor - Line: 1112
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Class: java.util.concurrent.ThreadPoolExecutor$Worker - Line: 587
05-10 00:32:45.279 2005-2156/org.fermat W/System.err: Class: java.lang.Thread - Line: 818

This occurs in both fan and artist.

In my updates i have I'm calling the following method: exposeIdentities().

@darkestpriest check this out in the ExposingData Classes.

**Comment by darkestpriest** [comment]
This exception is thrown by a test method or when you create an identity from UI?
If was throw by a test method, please, check if this identify is properly created.
