### ISSUE TITLE
ART Community Artist and Fan Bug

### ISSUE THREAD

**Issue by GaboHub** [Fermat-ORG/fermat#6185]
In Fan Community:

Fan1 sends invitation to Fan2, Fan2 received the invitation but enters other profile fragments and the bottom says "connect", Fan2 press the bottom and trys to sends invitation to user, causes following exception:

`Source: PluginVersionReference{pluginDeveloperReference=PluginDeveloperReference{pluginReference=PluginReference{layerReference=LayerReference{platformReference=PlatformReference{, platform=ART_PLATFORM}, layer=ACTOR_CONNECTION}, plugin=FAN_ACTOR_CONNECTION}, developer=BITDUBAI}, version=1.0.0}
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: ********************************************************************************************************************************************************
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Exception Number: 1
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Exception Type: class com.bitdubai.fermat_api.layer.actor_connection.common.exceptions.ActorConnectionAlreadyExistsException
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Exception Message: ACTOR CONNECTION ALREADY EXISTS EXCEPTION
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Exception Possible Cause: The connection already exists...
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Exception Context: 
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: actorConnection: ActorConnection{connectionId=8fd83f7c-0721-47c2-b8a5-67e483397198, linkedIdentity=LinkedActorIdentity{publicKey='04046D9CAA5EB8EF45608693E5153701EC0625CDFB0ADDD08EAEFB45167BEE2ABA5F0A6E7246C8CAA01D4777F160F8F41CB0C1CF98F33BC0FED43A5EEECC78290F', actorType=ART_FAN}, publicKey='044E9DF61C693B562EFC17CCDFD1E30D79CC5792798F1DDB0E35A670B5378ED255D4FDBE97A7220D76B14D9C28AA8538683167D1A835492C699A5F0EA8D292E614', alias='asdasdasd2', image=true, connectionState=PENDING_REMOTELY_ACCEPTANCE, creationTime=1463113802815, updateTime=1463113802815}
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Exception Stack Trace: 
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: com.bitdubai.fermat_api.layer.actor_connection.common.database_abstract_classes.ActorConnectionDao - Line: 140
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.actor_connection.fan.developer.bitdubai.version1.structure.ActorConnectionManager - Line: 137
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.sub_app_module.fan_community.developer.bitdubai.version_1.structure.FanCommunityManager - Line: 416
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: com.bitdubai.sub_app.fan_community.commons.popups.ConnectDialog - Line: 118
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: android.view.View - Line: 4780
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: android.view.View$PerformClick - Line: 19866
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: android.os.Handler - Line: 739
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: android.os.Handler - Line: 95
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: android.os.Looper - Line: 135
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: android.app.ActivityThread - Line: 5254
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: -2
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: 372
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit$MethodAndArgsCaller - Line: 903
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit - Line: 698
05-13 00:30:02.817 2586-2586/org.fermat W/System.err: ----------------------------------------------------------`

In Artist Community: 

Actors and able to sends to connection request to each other, but it shouldn't be that way.

I suggest that when a connection invitation arrives other profile fragment should display "accept" bottom.

@darkestpriest

**Comment by darkestpriest** [comment]
I think that we gonna show the *Accept Dialog* will be better in this case instead of show the other profile fragment, I'll check this bug and I'll fix it, thanks @GaboHub

**Comment by darkestpriest** [comment]
I fixed  the issue creating a logic that change the button text to accept request and runs the accept request procedure for this case.

**Comment by darkestpriest** [comment]
Fixed

**Comment by darkestpriest** [comment]
Fixed
