### ISSUE TITLE
TKY - Fan wallet - asyncTask bug

### ISSUE THREAD

**Issue by alexanderejm** [Fermat-ORG/fermat#6196]
with the following requirements
1) enter with a Art fan identity linked with a TKY fan identity
2) ART fan identity is conecte with an ART artist identity linked with a TKY artist identity

when entering the fan wallet for the first time the following error ocurs:

`05-16 22:06:09.928 3826-4940/org.fermat W/System.err: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at android.os.AsyncTask$3.done(AsyncTask.java:309)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err: Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at android.os.Handler.<init>(Handler.java:200)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at android.os.Handler.<init>(Handler.java:114)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at android.widget.Toast$TN.<init>(Toast.java:345)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at android.widget.Toast.<init>(Toast.java:101)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at android.widget.Toast.makeText(Toast.java:259)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at com.bitdubai.reference_wallet.fan_wallet.fragments.SongFragment$SyncThreadClass.doInBackground(SongFragment.java:1003)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at com.bitdubai.reference_wallet.fan_wallet.fragments.SongFragment$SyncThreadClass.doInBackground(SongFragment.java:958)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-16 22:06:09.928 3826-4940/org.fermat W/System.err: 	... 3 more
05-16 22:06:09.930 3826-3826/org.fermat I/System.out: TKY_ connection error`

@lostwood  pleaste take a look at it

EDIT: after further test, it was discovered to only occur on an API 23

**Comment by darkestpriest** [comment]
Please, @lostwood , take a look.

**Comment by lostwood** [comment]
i think with the new change in the asynctask. will fix this, so close this @darkestpriest when you can please
