### ISSUE TITLE
CCP-Loss Protected Wallet - Show Dialog Can't get exchange rate

### ISSUE THREAD

**Issue by nattyco** [Fermat-ORG/fermat#6204]
Cuando no se pueda recuperar el valor del exchange rate por problemas de conexion mostrar un dialog con un mensaje y un boton close.

**Comment by nattyco** [comment]
Add this dialog message on Send Fragment and Chunck Value Fragment

**Comment by gianelo** [comment]
Added on Send Fragment And Chunck Values

**Comment by nattyco** [comment]
Complete
