### ISSUE TITLE
TKY FAN WALLET notification to user when the internet is down

### ISSUE THREAD

**Issue by lostwood** [Fermat-ORG/fermat#6216]
When the internet is down, the download is freezing, so is required to notify the user of this situation

@darkespriest

**Comment by darkestpriest** [comment]
I think that you can check the internet status regularly from UI. The Fan wallet module has the method
```java
TokenlyAPIStatus getSwapBotAPIStatus()
```
This method checks if you can connect with Tokenly site, you can use this method to check if the internet is down
