### ISSUE TITLE
ART - Sub App - Fan and Artist Communities

### ISSUE THREAD

**Issue by GaboHub** [Fermat-ORG/fermat#6217]
When change between identities when one identity has a connection and the other doesn't causes this excepcion:
 com.bitdubai.fermat_art_api.layer.sub_app_module.community.fan.utils.FanCommunityInformationImpl cannot be cast to com.bitdubai.fermat_art_api.layer.sub_app_module.community.artist.interfaces.ArtistCommunityInformation
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at com.bitdubai.sub_app_artist_community.adapters.AppFriendsListAdapter.bindHolder(AppFriendsListAdapter.java:20)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at com.bitdubai.fermat_android_api.ui.adapters.FermatAdapter.onBindViewHolder(FermatAdapter.java:64)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at com.bitdubai.fermat_android_api.ui.adapters.FermatAdapter.onBindViewHolder(FermatAdapter.java:21)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5217)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5250)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4487)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
05-20 00:48:01.993 1659-1659/org.fermat W/System.err:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)

@darkestpriest

**Comment by darkestpriest** [comment]
Fixed
