### ISSUE TITLE
CCP- Sub App Community - Presentation Screen

### ISSUE THREAD

**Issue by nattyco** [Fermat-ORG/fermat#6243]
Add scroll on presentation screen layouts to can use the lower buttons in the API 16 and 17
This layout and layout whit identities button. On CCP Sub App Intra Wallet User Community
![community presentation](https://cloud.githubusercontent.com/assets/10051490/15509787/238d8c7c-21ab-11e6-89a4-e339dc226264.png)

**Comment by nattyco** [comment]
Complete

**Comment by nattyco** [comment]
En la version 4.1.1 no veo que pueda hacer el scroll, verificar tambien que el checkbox no se meta debajo del texto Don't Show this...

**Comment by clp3z** [comment]
Es que son dos dialogs. El que tiene los usuarios Jane y John Doe y éste. Entonces ambos tienen el problema.

**Comment by nattyco** [comment]
complete
