### ISSUE TITLE
CCP - Bitcoin Wallet - Presentation Dialogs

### ISSUE THREAD

**Issue by clp3z** [Fermat-ORG/fermat#6255]
![bcw_d1](https://cloud.githubusercontent.com/assets/8752959/15583174/339304fc-2364-11e6-9613-ca3efa88ef02.png)

![bcw_d2](https://cloud.githubusercontent.com/assets/8752959/15583182/3f7574e4-2364-11e6-9dda-953ceb869479.png)

![bcw_d3](https://cloud.githubusercontent.com/assets/8752959/15583195/5725ee48-2364-11e6-8efa-7a2d9dd64e76.png)

![bcw_d4](https://cloud.githubusercontent.com/assets/8752959/15714099/b77a8472-2808-11e6-9f4f-927392da2a4a.png)

## Issues

- [x] Wallet icon on the top left in pixelated
- [x] Checkbox overlapping TextView
- [x] Buttons have different height values
- [ ] A new checkbox button must be design for android version < 5.0 
- [x] ScrollView must cover all text fields

**Comment by nattyco** [comment]
complete
