### ISSUE TITLE
CSH - Cash Wallet - Allows make a Unhold on not Hold funds

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#6345]
We can make this test:
* Deposit funds 
* Make a hold (I used a test method present in Cash Money Hold Transaction Plugin Root), you can check the following picture:

![hold](https://cloud.githubusercontent.com/assets/10060413/16540218/6ed692e4-402a-11e6-8dcd-e48e105f56ef.png)
* After that, I make an unhold transaction over the previous Hold transaction and I got the following picture:

![unhold](https://cloud.githubusercontent.com/assets/10060413/16540222/998f77ee-402a-11e6-81ee-595d15ae98bc.png)
* You can see in the previous picture that I can make an unHold over not Hold fonds, also, this unhold rise my balance.

I can check this @franklinmarcano1970

**Comment by franklinmarcano1970** [comment]
Perfect...

**Comment by darkestpriest** [comment]
Fixed:
![unhold](https://cloud.githubusercontent.com/assets/10060413/16543321/a0678904-409c-11e6-9648-ac552a43556b.png)
